"""
Automated company discovery — runs on Celery beat schedule.
Probes Greenhouse, Lever, Ashby, SmartRecruiters, Workable,
BambooHR, Breezy HR, Recruitee, Workday, TeamTailor, Personio, iCIMS.
Also pulls company names from YC API and SEC EDGAR (~10k public companies).
Covers Fortune 500, Inc 5000, major US employers across all sectors.
Reads additional companies from /app/data/company_list.csv when present
(generated by scripts/build_company_list.py).
"""
import asyncio
import csv
import re
from datetime import datetime, timezone, timedelta
from pathlib import Path

import httpx
import structlog
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert

from app.workers.celery_app import celery_app
from app.database import AsyncSessionLocal, async_engine
from app.models.company import Company

logger = structlog.get_logger(__name__)

CONCURRENCY = 80
BATCH_LIMIT  = 5000


def _run_async(coro):
    async def _wrapper():
        await async_engine.dispose()
        return await coro
    return asyncio.run(_wrapper())


# ── Celery tasks ──────────────────────────────────────────────────────────────

@celery_app.task(name="app.workers.discovery_tasks.discover_companies_task",
                 soft_time_limit=7200, max_retries=1)
def discover_companies_task():
    """Weekly full automated company discovery across all ATS platforms."""
    return _run_async(_discover_async())


@celery_app.task(name="app.workers.discovery_tasks.discover_companies_quick",
                 soft_time_limit=600, max_retries=1)
def discover_companies_quick():
    """Quick daily discovery pass — top candidates only."""
    return _run_async(_discover_async(quick=True))


# ── 2000+ major US company names ──────────────────────────────────────────────

_US_COMPANY_NAMES: list[str] = [
    # Big Tech
    "Apple", "Microsoft", "Alphabet", "Google", "Amazon", "Meta", "Tesla",
    "NVIDIA", "Broadcom", "Oracle", "Salesforce", "Adobe", "Cisco", "Intel",
    "IBM", "Qualcomm", "Texas Instruments", "Applied Materials", "Lam Research",
    "KLA Corporation", "Micron Technology", "Western Digital", "Seagate",
    "HP Inc", "Dell Technologies", "VMware", "ServiceNow", "Workday",
    "Intuit", "Autodesk", "Palo Alto Networks", "CrowdStrike", "Fortinet",
    "Zscaler", "Okta", "Twilio", "Snowflake", "Databricks", "MongoDB",
    "Cloudflare", "Splunk", "Dynatrace", "New Relic", "Datadog",
    "Confluent", "HashiCorp", "Veeva Systems", "HubSpot",
    "Sprinklr", "Amplitude", "Braze", "Klaviyo", "Attentive",
    # Growth Tech
    "Atlassian", "Zoom", "DocuSign", "Box", "Dropbox", "Slack",
    "PagerDuty", "Asana", "Notion", "Airtable", "Figma", "Canva",
    "Miro", "Lucidchart", "Loom", "GitHub", "GitLab",
    "JFrog", "Sonatype", "Snyk", "Checkmarx", "Veracode",
    "Sourcegraph", "Replit", "CodeSandbox",
    "Stripe", "Plaid", "Braintree", "Adyen", "Square", "Block",
    "PayPal", "Affirm", "Klarna", "Afterpay", "Sezzle",
    "Chime", "Revolut", "SoFi", "LendingClub", "Upstart", "Blend",
    "Robinhood", "Coinbase", "Gemini", "Kraken",
    "Brex", "Ramp", "Divvy", "Airbase", "Procurify",
    "Gusto", "Rippling", "Lattice", "Culture Amp", "Leapsome",
    "15Five", "Betterworks", "Reflektive",
    "Greenhouse", "Lever", "Ashby", "Workable", "Jobvite",
    "BambooHR", "JazzHR", "Breezy HR", "Eightfold AI", "Beamery",
    "HireVue", "Spark Hire", "Karat", "HackerRank", "CodeSignal",
    "Udemy", "Coursera", "Pluralsight", "Degreed",
    "Intercom", "Drift", "Freshdesk", "Kustomer", "Help Scout",
    "Pipedrive", "Outreach", "SalesLoft", "Gong", "Chorus",
    "Clari", "Seismic", "Highspot", "Showpad",
    "Marketo", "Terminus", "Demandbase", "6sense",
    "Yelp", "Tripadvisor", "OpenTable", "Resy",
    "DoorDash", "Uber Eats", "Grubhub", "Instacart", "Gopuff",
    "Airbnb", "Vrbo", "Expedia", "Hopper",
    "Lyft", "Uber", "Via", "Alto",
    "Rivian", "Lucid Motors", "Fisker", "Canoo",
    "Waymo", "Cruise", "Aurora", "Zoox", "Mobileye", "Nuro",
    "SpaceX", "Blue Origin", "Rocket Lab", "Planet Labs",
    "Palantir", "Anduril", "Shield AI",
    # Finance & Banking
    "JPMorgan Chase", "Bank of America", "Citigroup", "Wells Fargo",
    "Goldman Sachs", "Morgan Stanley", "US Bancorp", "Truist Financial",
    "PNC Financial", "Capital One", "American Express", "Discover Financial",
    "Synchrony Financial", "Ally Financial", "Charles Schwab",
    "Fidelity Investments", "BlackRock", "State Street", "T Rowe Price",
    "Invesco", "Franklin Templeton", "Ameriprise", "Raymond James",
    "Edward Jones", "LPL Financial", "Stifel", "Piper Sandler",
    "William Blair", "Baird", "Lazard", "Evercore",
    "Moelis", "PJT Partners", "Houlihan Lokey",
    "Visa", "Mastercard", "FIS", "Fiserv", "Jack Henry",
    "NCR", "Nuvei", "Billtrust", "Bottomline Technologies",
    "Intercontinental Exchange", "Nasdaq", "CBOE", "CME Group",
    "Tradeweb", "MarketAxess", "FactSet", "MSCI", "Morningstar",
    "S&P Global", "Moody's", "Verisk Analytics", "Dun Bradstreet",
    "Equifax", "TransUnion", "Experian", "CoreLogic",
    # Insurance
    "Berkshire Hathaway", "MetLife", "Prudential Financial",
    "Lincoln National", "Unum Group", "Allstate", "Progressive",
    "Liberty Mutual", "Travelers", "Hartford Financial", "Chubb",
    "AIG", "Assurant", "Arch Capital", "Markel",
    "Hanover Insurance", "Cincinnati Financial", "Erie Indemnity",
    "Root Insurance", "Lemonade", "Hippo Holdings", "Next Insurance",
    # Healthcare Payers
    "UnitedHealth Group", "CVS Health", "Cigna", "Humana",
    "Elevance Health", "Centene", "Molina Healthcare",
    "Oscar Health", "Clover Health", "Alignment Healthcare",
    "Highmark", "Premera", "Regence", "Priority Health",
    # Pharma & Biotech
    "Johnson & Johnson", "Pfizer", "Merck", "AbbVie",
    "Bristol-Myers Squibb", "Eli Lilly", "Amgen", "Gilead Sciences",
    "Biogen", "Regeneron", "Moderna", "Vertex Pharmaceuticals",
    "Alnylam Pharmaceuticals", "Sarepta Therapeutics", "BioMarin",
    "Ionis Pharmaceuticals", "Intellia Therapeutics", "Editas Medicine",
    "CRISPR Therapeutics", "Beam Therapeutics", "Recursion Pharmaceuticals",
    "Viatris", "Teva Pharmaceutical", "Bausch Health",
    "Catalent", "Thermo Fisher Scientific", "Danaher",
    "Becton Dickinson", "Abbott Laboratories", "Baxter International",
    "Stryker", "Zimmer Biomet", "Intuitive Surgical",
    "Edwards Lifesciences", "Boston Scientific", "Medtronic",
    "ResMed", "Hologic", "DexCom", "Insulet", "Tandem Diabetes",
    "Globus Medical", "NuVasive", "Integra LifeSciences",
    # Hospital Systems
    "Mayo Clinic", "Cleveland Clinic", "Johns Hopkins Medicine",
    "Kaiser Permanente", "HCA Healthcare", "CommonSpirit Health",
    "Ascension Health", "Trinity Health", "Providence Health",
    "Dignity Health", "CHRISTUS Health", "Advocate Aurora Health",
    "Northwell Health", "NYU Langone Health", "Mount Sinai Health",
    "NewYork-Presbyterian", "Mass General Brigham",
    "Stanford Health Care", "UCSF Health", "Cedars-Sinai",
    "UCLA Health", "Scripps Health", "Sharp HealthCare",
    "Sutter Health", "Intermountain Health", "Banner Health",
    "Baylor Scott White Health", "Texas Health Resources",
    "MD Anderson", "Memorial Hermann", "Houston Methodist",
    "Tenet Healthcare", "Community Health Systems",
    "Prime Healthcare", "Lifepoint Health",
    "DaVita", "Amedisys", "LHC Group", "Kindred Healthcare",
    "Option Care Health",
    # Retail & Consumer
    "Walmart", "Costco", "Home Depot", "Target", "Kroger",
    "Walgreens Boots Alliance", "Lowe's", "Best Buy",
    "Dollar General", "Dollar Tree", "Albertsons",
    "Whole Foods Market", "Wegmans Food Markets",
    "Gap", "Old Navy", "Banana Republic", "Athleta",
    "American Eagle Outfitters", "Abercrombie Fitch",
    "Victoria's Secret", "Bath Body Works",
    "Nike", "Under Armour", "Lululemon", "Columbia Sportswear",
    "Nordstrom", "Macy's", "Bloomingdale's", "Neiman Marcus",
    "Saks Fifth Avenue", "JCPenney", "Dillard's", "Kohl's",
    "TJX Companies", "Ross Stores", "Burlington",
    "Wayfair", "Chewy", "Petco", "PetSmart", "GameStop",
    "Five Below", "AutoZone", "O'Reilly Auto Parts",
    "Advance Auto Parts", "Genuine Parts Company",
    "CarMax", "AutoNation", "Penske Automotive",
    "Lithia Motors", "Asbury Automotive",
    "Camping World", "REI", "DICK'S Sporting Goods",
    "Academy Sports", "Foot Locker", "Fanatics",
    "Williams-Sonoma", "Pottery Barn", "West Elm",
    "Staples", "Office Depot",
    "Ulta Beauty", "Sephora", "Sally Beauty",
    "Tiffany", "Signet Jewelers",
    # Food & Beverage / Restaurant
    "McDonald's", "Starbucks", "Chick-fil-A", "Taco Bell",
    "KFC", "Pizza Hut", "Burger King", "Popeyes", "Subway",
    "Domino's", "Papa Johns", "Dunkin", "Wendy's",
    "Sonic Drive-In", "Buffalo Wild Wings", "Arby's",
    "Jack in the Box", "Del Taco", "Carl's Jr", "Hardee's",
    "Denny's", "IHOP", "Applebee's", "Olive Garden",
    "LongHorn Steakhouse", "Red Lobster", "Outback Steakhouse",
    "Cheesecake Factory", "Red Robin", "Cracker Barrel",
    "Panera Bread", "Shake Shack", "Five Guys", "Wingstop",
    "Raising Cane's", "Chili's", "Texas Roadhouse",
    "Dutch Bros", "Peet's Coffee",
    "Keurig Dr Pepper", "Coca-Cola", "PepsiCo", "Monster Beverage",
    "Constellation Brands", "Anheuser-Busch", "Molson Coors",
    "Boston Beer", "Diageo", "Brown-Forman",
    "Nestle USA", "Kraft Heinz", "Conagra Brands",
    "General Mills", "Kellogg's", "Post Holdings",
    "Campbell Soup", "Hershey", "Mondelez International",
    "Tyson Foods", "JBS USA", "Smithfield Foods",
    "Pilgrim's Pride", "Perdue Farms",
    "Land O'Lakes", "Saputo USA", "Dairy Farmers of America",
    # Energy
    "ExxonMobil", "Chevron", "ConocoPhillips", "EOG Resources",
    "Pioneer Natural Resources", "Devon Energy", "Diamondback Energy",
    "Coterra Energy", "APA Corporation", "Ovintiv",
    "Range Resources", "Chesapeake Energy", "Southwestern Energy",
    "Antero Resources", "EQT Corporation",
    "Baker Hughes", "Halliburton", "SLB", "Weatherford",
    "TechnipFMC", "Oceaneering", "ChampionX",
    "Williams Companies", "Kinder Morgan", "Enterprise Products",
    "Energy Transfer", "Plains All American", "ONEOK", "Targa Resources",
    "NextEra Energy", "Duke Energy", "Southern Company",
    "Dominion Energy", "Exelon", "American Electric Power",
    "Xcel Energy", "PPL Corporation", "CMS Energy",
    "Entergy", "Edison International", "PG&E", "Sempra Energy",
    "Consolidated Edison", "National Grid", "Eversource Energy",
    "WEC Energy", "Alliant Energy",
    # Telecom
    "AT&T", "Verizon", "T-Mobile", "Comcast", "Charter Communications",
    "Cox Communications", "Altice USA", "Lumen Technologies",
    "Windstream", "Frontier Communications", "TDS Telecom",
    "Brightspeed", "Ziply Fiber", "MetroNet",
    "Dish Network", "DirecTV",
    # Media & Entertainment
    "Disney", "Netflix", "Warner Bros Discovery", "Paramount",
    "NBCUniversal", "Fox Corporation", "Sony Pictures Entertainment",
    "MGM", "Lionsgate", "A24", "Blumhouse", "AMC Networks",
    "AMC Theatres", "Regal Cinemas", "Cinemark",
    "iHeartMedia", "Audacy", "Cumulus Media",
    "Nexstar Media", "Gray Television", "Sinclair Broadcast",
    "Tegna", "E.W. Scripps", "TelevisaUnivision",
    "Clear Channel Outdoor", "Lamar Advertising", "Outfront Media",
    "DoubleVerify", "Integral Ad Science", "Zeta Global",
    "LiveRamp", "Acxiom", "Nielsen", "Comscore",
    "WPP", "Omnicom", "Publicis", "IPG", "Dentsu",
    "Edelman", "Weber Shandwick", "FleishmanHillard",
    # Manufacturing / Defense / Aerospace
    "Boeing", "Lockheed Martin", "Raytheon Technologies",
    "General Dynamics", "Northrop Grumman", "L3Harris Technologies",
    "BAE Systems", "Textron", "Curtiss-Wright", "TransDigm",
    "Heico", "Spirit AeroSystems", "Triumph Group",
    "Howmet Aerospace", "Precision Castparts",
    "Parker Hannifin", "Honeywell", "Eaton", "Emerson Electric",
    "Rockwell Automation", "Roper Technologies", "IDEX Corporation",
    "Illinois Tool Works", "Dover Corporation",
    "Caterpillar", "Deere & Company", "CNH Industrial",
    "AGCO Corporation", "Toro Company",
    "3M", "DuPont", "Dow Chemical", "Celanese",
    "Eastman Chemical", "Ashland Global",
    "Avery Dennison", "Sealed Air", "Berry Global",
    "Pactiv Evergreen", "Graphic Packaging", "WestRock",
    "International Paper", "Packaging Corporation of America",
    "GE Aerospace", "GE Healthcare", "GE Vernova",
    # Transportation & Logistics
    "UPS", "FedEx", "XPO Logistics", "C.H. Robinson",
    "J.B. Hunt Transport", "Werner Enterprises",
    "Schneider National", "Knight-Swift", "Old Dominion Freight",
    "Saia", "ABF Freight", "Forward Air", "Echo Global Logistics",
    "Total Quality Logistics", "Flexport", "project44", "FourKites",
    "Descartes Systems", "Hub Group", "Radiant Logistics", "RXO",
    "Ryder System", "GATX", "Greenbrier Companies",
    "CSX", "Union Pacific", "Norfolk Southern", "Amtrak",
    "Alaska Airlines", "American Airlines", "Delta Air Lines",
    "United Airlines", "Southwest Airlines", "JetBlue",
    "Spirit Airlines", "Frontier Airlines", "Allegiant Air",
    "Hawaiian Airlines", "SkyWest Airlines", "Republic Airways",
    # Real Estate & Construction
    "CBRE Group", "JLL", "Cushman Wakefield", "Colliers International",
    "Newmark", "Marcus Millichap",
    "AvalonBay Communities", "Equity Residential", "Essex Property Trust",
    "Camden Property Trust", "Invitation Homes", "American Homes 4 Rent",
    "Prologis", "Americold Realty", "Iron Mountain",
    "Equinix", "Digital Realty", "QTS Realty", "CyrusOne",
    "Simon Property Group", "Macerich", "Tanger Outlets",
    "AECOM", "Jacobs Engineering", "KBR", "Fluor",
    "Turner Construction", "Skanska USA", "Balfour Beatty",
    "Tutor Perini", "Granite Construction",
    "Comfort Systems USA", "EMCOR Group", "MYR Group",
    "Quanta Services", "Primoris Services",
    # Consulting & Professional Services
    "McKinsey Company", "Boston Consulting Group", "Bain Company",
    "Oliver Wyman", "Booz Allen Hamilton",
    "Accenture", "Deloitte", "PwC", "KPMG", "EY",
    "RSM US", "BDO USA", "Grant Thornton", "Moss Adams",
    "Baker Tilly", "Marcum", "CohnReznick",
    "FTI Consulting", "AlixPartners", "Guidehouse",
    "Huron Consulting", "ICF International",
    "Leidos", "SAIC", "ManTech", "CACI International",
    "Peraton", "Parsons Corporation", "Tetra Tech",
    "WSP USA", "Arcadis", "Burns McDonnell", "Black Veatch",
    "CDM Smith", "HNTB Corporation",
    "Gartner", "Forrester Research", "IDC",
    "Korn Ferry", "Spencer Stuart", "Heidrick Struggles",
    "IQVIA", "Parexel", "Syneos Health", "Covance",
    # Staffing & HR Tech
    "Adecco", "Manpower Group", "Robert Half", "Kforce",
    "Randstad", "Kelly Services", "Aerotek", "TEKsystems",
    "Insight Global", "Staffmark",
    "CDW", "Insight Direct", "SHI International", "World Wide Technology",
    "TriNet", "Insperity", "Paycor", "CBIZ",
    "ADP", "Paychex", "Ceridian", "UKG", "Paylocity", "Paycom",
    # Government Contractors
    "Mitre Corporation", "RAND Corporation", "Noblis",
    "Analytic Services", "LMI", "Alion Science", "Battelle Memorial",
    # Education
    "Pearson", "McGraw-Hill Education", "Cengage Learning",
    "Chegg", "Coursera", "edX", "Udacity", "Duolingo",
    "K12 Inc", "Stride", "Bright Horizons", "KinderCare",
    "Grand Canyon University", "Western Governors University",
    # Healthcare Tech
    "Epic Systems", "Cerner", "Allscripts", "athenahealth",
    "eClinicalWorks", "Meditech", "Netsmart Technologies",
    "Optum", "Cotiviti", "Multiplan", "Zelis Healthcare",
    "Availity", "Waystar", "InstaMed",
    "Exact Sciences", "Myriad Genetics", "Natera",
    "Foundation Medicine", "Guardant Health", "Grail", "Tempus",
    "Flatiron Health", "Komodo Health", "Health Catalyst",
    "Teladoc Health", "Amwell", "Hims Hers", "Ro",
    "Omada Health", "Virta Health", "Noom", "Calibrate",
    "Alto Pharmacy", "TruePill", "Capsule Pharmacy", "PillPack",
    # Cybersecurity
    "SentinelOne", "Darktrace", "Exabeam", "Illumio",
    "Lacework", "Orca Security", "Wiz",
    "Qualys", "Tenable", "Rapid7", "LogRhythm",
    "Secureworks", "Arctic Wolf", "eSentire",
    "ConnectWise", "Kaseya", "SolarWinds",
    "Proofpoint", "Mimecast", "Abnormal Security", "KnowBe4",
    "BeyondTrust", "CyberArk", "Delinea", "SailPoint", "Saviynt",
    # Data & Analytics
    "dbt Labs", "Fivetran", "Airbyte", "Talend", "Informatica",
    "MuleSoft", "SnapLogic", "Boomi", "Workato",
    "Tableau", "Looker", "Sisense", "ThoughtSpot",
    "Domo", "Qlik", "MicroStrategy",
    "Alteryx", "DataRobot", "H2O.ai", "Dataiku", "Domino Data Lab",
    # Cloud & DevOps
    "Red Hat", "SUSE", "Canonical",
    "Docker", "Rancher Labs",
    "Harness", "CircleCI", "BuildKite",
    "Grafana Labs", "InfluxData", "Elastic",
    # E-commerce & Marketplaces
    "Shopify", "BigCommerce",
    "eBay", "Etsy", "Poshmark", "ThredUp", "The RealReal",
    "StockX", "Goat", "Overstock",
    "Fastenal", "Grainger", "MSC Industrial",
    "WESCO International", "Graybar Electric",
    # Proptech & Mortgage
    "Opendoor", "Offerpad", "Redfin", "Compass",
    "Blend", "Better Mortgage", "Rocket Mortgage",
    "loanDepot", "Freedom Mortgage", "Movement Mortgage",
    "Guild Mortgage", "CrossCountry Mortgage",
    # Additional Major US Employers
    "HP Enterprise", "DXC Technology", "Unisys", "Xerox",
    "Pitney Bowes", "Conduent", "Maximus",
    "Motorola Solutions", "Axon Enterprise",
    "ViaSat", "Hughes Network", "EchoStar",
    "SBA Communications", "Crown Castle", "American Tower",
    "Akamai Technologies", "Imperva", "Neustar", "Verisign",
    "GoDaddy", "Web.com", "WP Engine",
    "Automattic", "Medium", "Substack",
    "Hootsuite", "Sprout Social", "Buffer",
    "Toast", "Olo", "Lightspeed",
    "Zendesk", "Freshworks", "Intercom",
    "Productboard", "LaunchDarkly", "Split", "Statsig", "Optimizely",
    "FullStory", "Heap", "Hotjar", "Contentsquare",
    "Qualtrics", "Medallia", "InMoment", "Alchemer",
    "SurveyMonkey", "Typeform", "Jotform", "Formstack",
    "Loom", "Vidyard", "Wistia", "Vimeo", "Brightcove",
    "RingCentral", "8x8", "Vonage", "Dialpad", "Aircall",
    "Talkdesk", "NICE", "Genesys", "Five9", "Avaya",
    "Webflow", "Bubble", "OutSystems", "Mendix",
    "Appian", "Pega", "Nintex", "ServiceNow",
    # Additional Startups / Scale-ups
    "Deel", "Remote", "Papaya Global", "Oyster HR",
    "Velocity Global", "Globalization Partners",
    "Checkout.com", "Rapyd", "Airwallex", "Wise", "Remitly",
    "Carta", "Capchase", "Pipe",
    "Benchling", "Synthego", "Twist Bioscience",
    "Samsara", "Verkada", "Ambient AI",
    "Duolingo", "Masterclass", "Brilliant",
    "Opendoor", "Offerpad", "Redfin", "Compass",
    "Ro", "Hims Hers", "Thirty Madison",
    "Noom", "Omada Health", "Virta Health",
    "Alto Pharmacy", "TruePill", "Capsule",
    "Carvana", "Vroom", "Shift Technologies",
    "Outdoorsy", "RVshare", "Turo", "Getaround",
    "Sonder", "Vacasa", "Evolve Vacation", "AvantStay",
    "Hippo Insurance", "Branch Insurance", "Root Insurance",
    "Kin Insurance", "Openly", "Next Insurance", "Clearcover",
    "Ethos Life", "Bestow", "Fabric",
    "Cityblock Health", "Firefly Health", "Crossover Health",
    "Carbon Health", "Forward", "One Medical",
    "Spring Health", "Lyra Health", "Modern Health", "Headway",
    "Brightline", "Cerebral", "Done", "Ahead",
    "GoodRx", "RxSense", "Blink Health", "Rx Savings Solutions",
    "Transcarent", "Quantum Health", "Accolade", "Healthjoy",
    "Collective Health", "Bind", "Gravie",
    "Capsule Pharmacy", "NimbleRx", "ScriptDrop",
]


# Known Ashby customers — these slugs are their exact registered handles
_ASHBY_KNOWN_SLUGS: list[str] = [
    "openai", "anthropic", "notion", "linear", "figma", "vercel",
    "supabase", "stripe", "brex", "ramp", "rippling", "gusto",
    "lattice", "carta", "airbnb", "databricks", "snowflake",
    "retool", "segment", "mixpanel", "amplitude", "launchdarkly",
    "loom", "miro", "canva", "webflow", "airtable", "coda",
    "superhuman", "mercury", "deel", "remote",
    "scale-ai", "cohere", "stability-ai",
    "runway", "hugging-face", "replit", "sourcegraph",
    "clickup", "samsara", "verkada",
    "benchling", "arcadia", "komodo-health", "flatiron-health",
    "ro", "hims-hers", "noom", "calibrate",
    "duolingo", "coursera", "masterclass", "brilliant",
    "dbt-labs", "fivetran", "airbyte", "hightouch",
    "census", "rudderstack", "productboard",
    "heap", "fullstory", "hotjar", "contentsquare",
    "applovin", "unity-technologies",
    "epic-games", "riot-games", "niantic", "discord",
    "algolia", "elastic",
    "clearbit", "zoominfo", "lusha", "apollo",
    "outreach", "salesloft", "gong", "chorus",
    "clari", "people-ai",
    "betterworks", "culture-amp", "leapsome", "15five",
    "envoy", "robin",
    "personio", "hibob", "factorial",
    "secureframe", "drata", "vanta",
    "anrok", "taxjar", "avalara",
    "intercom", "freshdesk", "helpscout", "gladly", "kustomer", "gorgias",
    "pagerduty", "incident-io", "rootly", "blameless", "firehydrant",
    "grafana", "datadog", "newrelic", "dynatrace",
    "sentry", "rollbar", "bugsnag",
    "hashicorp", "pulumi", "env0", "spacelift",
    "harness", "codefresh", "circleci", "buildkite",
    "netlify", "cloudflare", "fastly", "akamai",
    "render", "railway", "fly-io",
    "tailscale", "ngrok",
    "ironclad", "spotdraft", "contractbook", "juro",
    "docsend", "pandadoc", "proposify",
    "braze", "iterable", "klaviyo",
    "attentive", "postscript", "sendbird",
    "twilio", "bandwidth", "vonage",
    "braintree", "adyen", "checkout", "rapyd",
    "plaid", "finicity", "mx-technologies",
    "expensify", "navan", "brex",
    "coupa", "procurify", "zip", "vendr",
    "docusign", "hellosign", "pandadoc",
    "okta", "onelogin", "auth0", "ping-identity",
    "cyberark", "beyondtrust", "sailpoint", "saviynt",
    "crowdstrike", "sentinelone", "carbon-black",
    "qualys", "tenable", "rapid7",
    "proofpoint", "mimecast", "abnormal-security", "knowbe4",
    "shopify", "bigcommerce",
    "klaviyo", "attentive",
    "gorgias", "richpanel", "reamaze",
    "shipstation", "shipbob", "easypost",
    "avalara", "taxjar",
    "semrush", "ahrefs", "moz", "conductor", "brightedge",
    "similarweb", "comscore",
    "hotjar", "crazy-egg", "mouseflow", "fullstory", "heap",
    "segment", "rudderstack", "mparticle", "tealium",
    "appsflyer", "branch", "adjust", "singular", "kochava",
    "impact", "partnerstack", "shareasale",
]


# Known Workable customers
_WORKABLE_KNOWN_SLUGS: list[str] = [
    "hubspot", "hootsuite", "sproutsocial", "buffer",
    "mailchimp", "constantcontact", "activecampaign",
    "zendesk", "freshworks", "helpscout", "intercom", "drift",
    "talkdesk", "five9", "genesys", "aircall", "cloudtalk", "dialpad",
    "ringcentral", "vonage",
    "zoom", "webex", "gotomeeting",
    "docusign", "adobe-sign", "hellosign", "pandadoc",
    "box", "dropbox", "egnyte",
    "slack", "asana", "monday", "clickup", "teamwork", "wrike",
    "basecamp", "smartsheet", "airtable", "trello",
    "jira", "confluence", "notion", "github", "gitlab",
    "circleci", "travis-ci", "buildkite",
    "datadog", "newrelic", "splunk", "sumo-logic",
    "elastic", "grafana",
    "tableau", "looker", "domo", "qlik",
    "salesforce", "hubspot", "zoho", "pipedrive",
    "outreach", "salesloft", "apollo", "clearbit",
    "zoominfo",
    "stripe", "braintree", "paypal", "square",
    "quickbooks", "xero", "freshbooks",
    "netsuite", "sage", "epicor", "infor",
    "bamboohr", "adp", "paychex", "gusto", "rippling",
    "lattice", "culture-amp", "15five", "betterworks",
    "checkr", "sterling", "hireright", "first-advantage",
    "docebo", "cornerstone", "skillsoft", "degreed",
    "mimecast", "proofpoint", "knowbe4", "cofense",
    "crowdstrike", "sentinelone", "carbon-black",
    "okta", "onelogin", "ping-identity", "auth0",
    "cyberark", "beyondtrust", "sailpoint",
    "qualys", "tenable", "rapid7",
    "shopify", "bigcommerce",
    "klaviyo", "attentive", "postscript",
    "yotpo", "stamped", "loox", "okendo",
    "gorgias", "tidio",
    "shipstation", "shipbob", "easypost", "stamps",
    "avalara", "taxjar", "vertex",
    "podium", "birdeye", "reputation", "yext",
    "semrush", "ahrefs", "moz",
    "hotjar", "crazy-egg", "mouseflow", "fullstory", "heap",
    "segment", "rudderstack", "mparticle", "tealium",
    "appsflyer", "branch", "adjust", "singular",
    "impact", "partnerstack",
]


# Known BambooHR customers
_BAMBOOHR_KNOWN_SLUGS: list[str] = [
    "soundcloud", "glassdoor", "vimeo", "disqus", "foursquare",
    "fitbit", "surveymonkey", "squarespace", "zenefits",
    "thinkmodo", "coyote-logistics", "placeiq", "movableink",
    "bonobos", "warbyparker", "casper", "allbirds", "bombas",
    "patagonia", "rei", "everlane", "untuckit", "faherty",
    "fanatics", "fandango", "stubhub", "vividseats",
    "ticketmaster", "livenation", "axs",
    "headspace", "calm", "insight-timer",
    "classpass", "mindbody", "gympass",
    "peloton", "mirror",
    "hinge", "bumble", "match", "plentyoffish",
    "zillow", "realtor", "redfin", "compass",
    "opendoor", "offerpad",
    "wework", "industrious", "commondesk", "iw",
    "shipbob", "shipstation", "shiphero",
    "flexport", "project44",
    "convoy", "transfix",
    "rubrik", "cohesity", "commvault",
    "nutanix", "pure-storage", "netapp",
    "aruba", "juniper",
    "zoom-video", "ringcentral", "8x8",
    "zendesk", "freshdesk", "helpscout",
    "hubspot", "marketo",
    "optimizely", "abobe", "coveo",
    "bazaarvoice", "powerreviews", "yotpo",
    "brainware", "plex", "infor",
    "epicor", "sap", "workday",
    "cornerstone", "sumtotal", "saba",
    "docebo", "litmos", "absorblms",
    "expensify", "concur", "navan",
    "coupa", "procurify", "tipalti",
    "bill", "melio", "routable",
    "chargebee", "recurly", "zuora",
    "stripe", "braintree", "adyen",
]

# Known Breezy HR customers
_BREEZY_KNOWN_SLUGS: list[str] = [
    "mediaspark", "flodesign", "acquia", "wpengine", "pantheon",
    "buzzfeed", "vox-media", "insider-inc",
    "condé-nast", "meredith", "hearst",
    "quora", "medium", "substack",
    "capterra", "g2", "trustradius", "getapp",
    "clutch", "goodfirms",
    "toptal", "upwork", "freelancer",
    "99designs", "crowdspring", "designcrowd",
    "fiverr", "guru",
    "topcoder", "hackerearth",
    "legalzoom", "rocket-lawyer", "nolo",
    "clio", "mycase", "practicepanther",
    "mindbody", "acuity", "calendly",
    "eventbrite", "cvent", "bizzabo",
    "hopin", "airmeet", "run-the-world",
    "typeform", "jotform", "wufoo",
    "surveymonkey", "qualtrics", "medallia",
    "hotjar", "lucky-orange", "crazzyegg",
    "freshbooks", "xero", "wave",
    "harvest", "toggl", "clockify",
    "hubstaff", "time-doctor", "desktime",
    "bamboohr", "zenefits", "namely",
    "greenhouse", "lever", "jobvite",
    "paylocity", "paycom", "paycor",
    "ceridian", "ukg", "kronos",
    "insperity", "trinet", "justworks",
    "remote", "deel", "papaya-global",
    "velocity-global", "oyster",
]

# ── Workday: known tenant slugs (Fortune 500 + major employers) ──────────────
# Workday subdomains follow: {slug}.wd{N}.myworkdayjobs.com
_WORKDAY_KNOWN_SLUGS: list[str] = [
    # Big Tech
    "amazon", "microsoft", "apple", "google", "meta", "netflix",
    "ibm", "oracle", "sap", "salesforce", "adobe", "vmware",
    "cisco", "intel", "qualcomm", "nvidia", "broadcom", "amd",
    "hp", "dell", "emc", "lenovo", "motorola",
    # Finance
    "jpmorgan", "bankofamerica", "wellsfargo", "citigroup",
    "goldmansachs", "morganstanley", "americanexpress", "capitalone",
    "discoverfinancial", "usbank", "pnc", "truist",
    "charlesschwab", "fidelity", "blackrock", "statestreet",
    "visa", "mastercard", "paypal", "fis", "fiserv",
    "intercontinentalexchange", "nasdaq", "cme",
    "equifax", "transunion", "moodys", "sandp",
    # Insurance
    "berkshirehathaway", "metlife", "prudential", "lincolnnational",
    "allstate", "progressive", "libertymutual", "travelers",
    "hartford", "chubb", "aig", "cigna", "humana",
    "unitedhealth", "cvs", "elevance", "centene",
    # Healthcare
    "johnsonandjohnson", "pfizer", "merck", "abbvie",
    "bristolmyerssquibb", "elililly", "amgen", "gilead",
    "biogen", "regeneron", "abbvie", "baxter",
    "medtronic", "stryker", "bostonscientific",
    "thermofisher", "danaher", "bectondickinson", "abbott",
    "hca", "davita", "laboratorycorp", "questdiagnostics",
    "teladoc", "cigna",
    # Retail
    "walmart", "target", "costco", "homedepot", "lowes",
    "bestbuy", "kroger", "albertsons", "publix",
    "dollar-general", "dollartree",
    "gap", "nike", "underarmour", "lululemon",
    "nordstrom", "macys", "tjx", "ross",
    "wayfair", "chewy",
    # Food & Beverage
    "mcdonalds", "starbucks", "yum", "restaurant-brands",
    "dominos", "chipotle", "darden",
    "cocacola", "pepsico", "keurigdrpepper",
    "kraftheinz", "conagra", "generalmills", "kellogg",
    "tysonfoods",
    # Energy
    "exxonmobil", "chevron", "conocophillips", "eog",
    "pioneernatural", "devon", "halliburton", "bakerhughes",
    "slb", "williamcompanies", "kindermorgan",
    "nextera", "duke", "southernco", "dominion", "exelon",
    "americanelectric", "xcel",
    # Telecom
    "att", "verizon", "tmobile", "comcast", "charter",
    "cox",
    # Media / Entertainment
    "disney", "warnerbros", "paramount", "nbcuniversal",
    "sony", "foxcorporation",
    "spotify", "pandora",
    # Aerospace / Defense
    "boeing", "lockheedmartin", "raytheon", "northropgrumman",
    "generaldynamics", "l3harris", "textron",
    "baesystems", "transdigm",
    "ge", "honeywell", "parkerhanifin", "emerson",
    "3m", "dupont", "dow",
    # Logistics
    "ups", "fedex", "xpo", "chrobinson",
    "jbhunt", "schneider", "werner",
    "csx", "unionpacific", "norfolksouthern",
    # Consulting
    "accenture", "deloitte", "pwc", "kpmg", "ey",
    "mckinsey", "bcg", "bain",
    "boozallen", "leidos", "saic",
    "iqvia", "parexel",
    # Other major employers
    "aecom", "jacobs", "fluor", "kbr",
    "adp", "paychex", "ceridian", "ukg",
    "manpowergroup", "adecco", "randstad",
    "gartner", "idc",
    "gsk", "astrazeneca", "novartis", "roche",
    "unilever", "nestle", "danone",
    "toyota", "honda", "ford", "gm",
    "siemens", "philips", "bosch",
    "loreal", "procter", "pg",
]

# ── TeamTailor: primarily European scale-ups ─────────────────────────────────
_TEAMTAILOR_KNOWN_SLUGS: list[str] = [
    # German/Austrian/Swiss
    "personio", "n26", "sumup", "holidu", "contentful",
    "thermondo", "rewave", "about-you", "westwing", "home24",
    "gorillas", "flink", "getir-de", "jokr",
    "babbel", "lingoda", "blinkist", "clue",
    "auxmoney", "smava", "clark-de", "wefox", "getsafe",
    "trade-republic", "scalable-capital", "justtrade",
    "flaconi", "outfittery", "aboutyou", "mytheresa",
    "sixt", "flixbus", "door2door",
    "rewe-digital", "edeka-digital", "kaufland", "lidl-digital",
    "freeletics", "gymondo", "yazio",
    "urbanara", "westwing-group",
    "pitch", "miro", "loom-de",
    "signavio", "celonis", "serviceform",
    "comtravo", "airhelp", "fairfleet",
    "omio", "goeuro",
    # Nordic
    "klarna", "spotify", "king", "mojang",
    "voi-technology", "tier-mobility", "bolt-eu",
    "hemnet", "blocket", "tradera",
    "bambuser", "wrapp",
    "izettle", "trustly", "bambora",
    "tink", "meniga", "moneymeets",
    "meltwater", "unacast",
    "kahoot", "visma", "tripletex",
    "peltarion", "cygni", "sinch",
    "wolt-nordic",
    # UK
    "monzo", "starling-bank", "revolut-uk",
    "funding-circle", "zopa", "oaknorth",
    "farfetch", "notonthehighstreet", "made-com",
    "deliveroo", "citymapper", "depop",
    "onfido", "cleo", "curve",
    "healx", "benevolentai", "exscientia",
    "babylon-health", "cera",
    "cazoo", "cinch", "motorway",
    "phoebe-media",
    # Benelux
    "booking", "adyen-careers", "mollie",
    "coolblue", "bol-com", "wehkamp",
    "takeaway", "thuisbezorgd",
    "messagebird", "sendcloud", "channelengine",
    "catawiki", "vinted-eu",
    "temper", "youngcapital",
    # Southern Europe
    "wallapop", "glovo", "cabify",
    "jobandtalent", "cornerstone-es",
    "zalando-es", "mango",
    # Eastern Europe / Global
    "wrike", "grammarly", "gitlab-eu",
    "pipedrive", "transferwise",
    "bolt", "taxify", "zego",
    "treatwell", "planday",
]

# ── Personio: German-speaking companies + broader EU ─────────────────────────
_PERSONIO_KNOWN_SLUGS: list[str] = [
    # German tech/startups
    "babbel", "contentful", "sennheiser", "magazino",
    "personio-customers", "forto", "unu-motors",
    "thermondo", "zolar", "sonnen", "envio",
    "smava", "auxmoney", "crosslend", "raisin",
    "urban-sports-club", "fitogram", "eversports",
    "flaconi", "otto-group-digital", "bonprix",
    "rewe-group", "tegut", "dm-drogerie",
    "sixt-leasing", "arval", "alphabet-fleet",
    "kuka", "trumpf", "festo", "schunk",
    "wirecard", "teamviewer", "nemetschek",
    "atoss", "cevotec", "isar-aerospace",
    "lilium", "volocopter", "wingcopter",
    "celonis", "signavio-sap", "qualtrics-eu",
    "haufe-group", "wolterskluwer-de",
    "fabian", "merantix", "twenty-bn",
    "wunderflats", "homeday", "McMakler",
    "myfitness", "oatsome", "nu3",
    "notino", "flaschenpost",
    "hellofresh-de", "marley-spoon",
    "liefery", "tiramizoo", "urbantz",
    "smartly-io", "adjust-mobile",
    # Austrian
    "dynatrace", "imoveis", "runtastic-adidas",
    "willhaben", "shpock", "styria",
    # Swiss
    "doodle", "smallpdf", "stash",
    "bexio", "klara", "abacus-research",
    "swisscom", "mobilezone", "digital-barriers",
    # Other European
    "younited-credit", "lydia-app", "payfit",
    "spendesk", "pento", "factorial-hr",
    "coverflex", "remote-de",
]

# ── iCIMS: US mid-market and large employers ──────────────────────────────────
_ICIMS_KNOWN_SLUGS: list[str] = [
    # Retail & Consumer
    "petsmart", "petco-icims", "hobby-lobby",
    "autozone-icims", "oreilly", "advanceauto",
    "michaels", "jo-ann", "ac-moore",
    "tj-maxx-icims", "marshalls", "homegoods",
    "harley-davidson", "polaris", "brunswick",
    "tiffanyco", "signet",
    # Food & Restaurant
    "panera", "dennys", "ihop",
    "applebees", "olivegarden", "redlobster",
    "crackerbarrel", "darden-icims",
    "nathansfamous", "sbarro",
    # Healthcare / Pharma
    "hologic", "integra", "globusmedical",
    "nuvectra", "exactsciences",
    "corcept", "mirati", "kala-pharma",
    "communityhealth", "lifepoint-health",
    "prime-healthcare", "tenet-health",
    "bayada", "amedisys-icims",
    "concentra", "teamhealth",
    # Finance / Insurance
    "pnc-icims", "synchrony", "ally",
    "hanover-insurance", "cincinnati-financial",
    "erie-insurance", "nationwide-icims",
    "principal-financial", "ameritas",
    "pacific-life", "protective",
    "assurant-icims", "unum-group",
    # Manufacturing / Industrial
    "parker-hannifin", "kennametal", "watts-water",
    "rexnord", "roper-tech", "idex-corp",
    "watts-water", "circor", "moog",
    "curtiss-wright", "triumph-group",
    "ducommun", "kaman", "heico-icims",
    "standex", "kaydon", "kaydon",
    "ferro", "innospec", "quaker-houghton",
    "cabot", "stepan", "balchem",
    "lydall", "myers-industries", "greif",
    "pactiv-evergreen", "sealed-air-icims",
    # Energy
    "range-resources", "eqt-icims",
    "crc", "sm-energy", "bonanza-creek",
    "hi-crush", "solaris-oilfield",
    "archrock", "select-water",
    "dcp-midstream", "crossamerica",
    # Technology / Services
    "cdw", "insight-direct", "shi-int",
    "presidio", "forsythe",
    "anixter", "belden", "commscope-icims",
    "ciena", "viavi", "calix",
    "syniverse", "liqtech",
    "modis", "staffmark", "spherion",
    "volt", "adia", "advantage",
    # Consulting / Government
    "mitre-icims", "anser", "lmi-icims",
    "aptive", "saic-icims", "caci-icims",
    "parsons-icims", "tetra-tech",
    "environmental-systems", "arcadis-icims",
]

# Known Recruitee customers
_RECRUITEE_KNOWN_SLUGS: list[str] = [
    "babbel", "blinkist", "contentful", "personio", "gorillas",
    "n26", "trade-republic", "solarisbank", "clark",
    "hellofresh", "flixbus", "auto1-group", "delivery-hero",
    "zalando", "trivago", "booking", "aboutyou",
    "westwing", "home24",
    "sumup", "paysend", "paysafe", "wise",
    "klarna", "adyen",
    "messagebird", "sendcloud", "channelengine",
    "catawiki", "vinted", "wallapop",
    "miro", "pitch", "loom",
    "typeform", "factorial",
    "jobandtalent", "cornerjob", "infojobs",
    "wolterskluwer", "elsevier", "springer-nature",
    "philips", "asml", "nxp", "imec",
    "coolblue", "wehkamp", "bol",
    "booking", "tripadvisor",
    "cnx-group", "unit4", "sdworx",
    "coosto", "spotler", "copernica",
    "youngcapital", "tempo-team", "yacht",
    "nationale-nederlanden", "aegon", "asr",
    "rabobank", "abn-amro", "ing",
    "deloitte-nl", "kpmg-nl",
    "albert-heijn", "jumbo", "lidl",
    "ahold", "unilever", "heineken",
    "dsm", "akzonobel", "arcadis",
    "royaldutchshell", "total",
]


_CSV_PATH = Path("/app/data/company_list.csv")


def _load_csv_companies() -> list[dict]:
    """
    Load companies from /app/data/company_list.csv (built by build_company_list.py).
    Returns a list of dicts with keys: name, domain, industry, country,
    size_range, priority_score.  Returns [] if the file doesn't exist yet.
    """
    if not _CSV_PATH.exists():
        logger.info("company_csv_not_found", path=str(_CSV_PATH))
        return []
    rows: list[dict] = []
    try:
        with _CSV_PATH.open(newline="", encoding="utf-8") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                name = (row.get("name") or "").strip()
                if name:
                    rows.append({
                        "name":           name,
                        "domain":         (row.get("domain") or "").strip() or None,
                        "industry":       (row.get("industry") or "").strip() or None,
                        "country":        (row.get("country") or "US").strip() or "US",
                        "priority_score": _safe_int(row.get("priority_score"), 50),
                    })
        logger.info("company_csv_loaded", count=len(rows), path=str(_CSV_PATH))
    except Exception as exc:
        logger.warning("company_csv_read_error", error=str(exc))
    return rows


def _safe_int(val, default: int) -> int:
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def _derive_slugs(name: str) -> list[str]:
    """Derive candidate ATS slugs from a company name."""
    n = name.lower()
    for suffix in [" inc", " corp", " ltd", " llc", " technologies",
                   " systems", " solutions", " software", " labs", " ai",
                   " tech", ", inc", ", corp", ", ltd", ".", ",",
                   " company", " group", " holdings", " brands",
                   " enterprises", " international", " global",
                   " services", " consulting", " management",
                   " partners", " associates", " agency",
                   " health", " healthcare", " financial", " capital"]:
        n = n.replace(suffix, "")
    n = n.strip()
    h = re.sub(r"[^a-z0-9]+", "-", n).strip("-")
    plain = re.sub(r"[^a-z0-9]+", "", n)
    candidates = [h, plain]
    if h.endswith("-ai"):
        candidates.append(h[:-3])
    for word in ["-technologies", "-systems", "-solutions", "-software",
                 "-health", "-healthcare", "-financial", "-capital",
                 "-analytics", "-platform", "-group"]:
        if h.endswith(word):
            candidates.append(h[: -len(word)])
    return list(dict.fromkeys(s for s in candidates if len(s) >= 2))


# ── ATS probe helpers ─────────────────────────────────────────────────────────

async def _check_greenhouse(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs", timeout=7)
        return r.status_code == 200 and len(r.json().get("jobs", [])) > 0
    except Exception:
        return False


async def _check_lever(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://api.lever.co/v0/postings/{slug}?mode=json&limit=1", timeout=7)
        data = r.json()
        return r.status_code == 200 and isinstance(data, list) and len(data) > 0
    except Exception:
        return False


async def _check_ashby(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://api.ashbyhq.com/posting-api/job-board/{slug}", timeout=7)
        return r.status_code == 200 and len(r.json().get("jobPostings", [])) > 0
    except Exception:
        return False


async def _check_smartrecruiters(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://api.smartrecruiters.com/v1/companies/{slug}/postings",
            params={"limit": 1}, timeout=7)
        return r.status_code == 200 and len(r.json().get("content", [])) > 0
    except Exception:
        return False


async def _check_workable(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.post(
            f"https://apply.workable.com/api/v3/accounts/{slug}/jobs",
            json={"limit": 1}, timeout=7)
        return r.status_code == 200 and len(r.json().get("results", [])) > 0
    except Exception:
        return False


async def _check_bamboohr(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://{slug}.bamboohr.com/jobs/embed2.php", timeout=8)
        if r.status_code != 200:
            return False
        # A valid BambooHR embed page contains job data JS
        return "BambooHR" in r.text and len(r.text) > 1000
    except Exception:
        return False


async def _check_breezy(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://{slug}.breezy.hr/json", timeout=7)
        if r.status_code != 200:
            return False
        data = r.json()
        positions = data.get("positions", []) if isinstance(data, dict) else []
        return len(positions) > 0
    except Exception:
        return False


async def _check_recruitee(client: httpx.AsyncClient, slug: str) -> bool:
    try:
        r = await client.get(
            f"https://{slug}.recruitee.com/api/offers/?scope=published&limit=1",
            timeout=7)
        if r.status_code != 200:
            return False
        data = r.json()
        return len(data.get("offers", [])) > 0 if isinstance(data, dict) else False
    except Exception:
        return False


# Workday WD version numbers to try (cover 95% of tenants)
_WD_VERSIONS = ("wd1", "wd2", "wd3", "wd5", "wd12")


async def _check_workday(client: httpx.AsyncClient, slug: str) -> str | None:
    """Returns 'slug.wdN' ATS identifier if a live Workday tenant is found."""
    for wd in _WD_VERSIONS:
        try:
            r = await client.get(
                f"https://{slug}.{wd}.myworkdayjobs.com",
                timeout=8,
            )
            # Valid Workday tenants return 200 with the WD JS app
            if r.status_code == 200 and "workday" in r.text.lower():
                return f"{slug}.{wd}"
        except Exception:
            pass
    return None


async def _check_teamtailor(client: httpx.AsyncClient, slug: str) -> bool:
    """TeamTailor: {slug}.teamtailor.com/jobs.json"""
    try:
        r = await client.get(
            f"https://{slug}.teamtailor.com/jobs.json", timeout=7)
        if r.status_code != 200:
            return False
        data = r.json()
        return isinstance(data, dict) and len(data.get("jobs", [])) > 0
    except Exception:
        return False


async def _check_personio(client: httpx.AsyncClient, slug: str) -> bool:
    """Personio: {slug}.jobs.personio.de/xml or .com/xml"""
    for domain in (
        f"https://{slug}.jobs.personio.de",
        f"https://{slug}.jobs.personio.com",
    ):
        try:
            r = await client.get(f"{domain}/xml", timeout=7)
            if (
                r.status_code == 200
                and len(r.text) > 300
                and ("<position" in r.text.lower() or "<jobs" in r.text.lower())
            ):
                return True
        except Exception:
            pass
    return False


async def _check_icims(client: httpx.AsyncClient, slug: str) -> bool:
    """iCIMS: {slug}.icims.com/jobs/intro"""
    try:
        r = await client.get(
            f"https://{slug}.icims.com/jobs/intro", timeout=8)
        return r.status_code in (200, 301, 302) and "icims" in r.text.lower()
    except Exception:
        return False


# ── YC company fetch ──────────────────────────────────────────────────────────

async def _fetch_yc_names(client: httpx.AsyncClient) -> list[str]:
    """Return all YC company names via their public API."""
    names: list[str] = []
    page = 1
    while True:
        try:
            r = await client.get(
                "https://api.ycombinator.com/v0.1/companies",
                params={"page": page, "per_page": 100},
                timeout=15,
            )
            if r.status_code != 200:
                break
            batch = r.json().get("companies", [])
            if not batch:
                break
            for c in batch:
                if c.get("name"):
                    names.append(c["name"])
            page += 1
            if page > 200:
                break
        except Exception as e:
            logger.warning("yc_fetch_error", error=str(e))
            break
    return names


async def _fetch_sec_edgar_names(client: httpx.AsyncClient) -> list[str]:
    """Fetch ~10,000 public US company names from SEC EDGAR company_tickers.json."""
    names: list[str] = []
    try:
        r = await client.get(
            "https://www.sec.gov/files/company_tickers.json",
            headers={"User-Agent": "JobJarvis/1.0 ramvamshikrishna0@gmail.com"},
            timeout=20,
        )
        if r.status_code == 200:
            data = r.json()
            for entry in data.values():
                title = entry.get("title", "")
                if title and len(title) > 1:
                    names.append(title.title())
    except Exception as e:
        logger.warning("sec_edgar_fetch_error", error=str(e))
    logger.info("sec_edgar_names", count=len(names))
    return names


async def _get_existing_slugs(db) -> set[str]:
    r = await db.execute(select(Company.ats_identifier))
    return {row[0] for row in r.fetchall() if row[0]}


async def _insert_company(
    db,
    name: str,
    ats_type: str,
    slug: str,
    domain: str | None = None,
    priority_score: int = 50,
    country: str = "US",
):
    stmt = pg_insert(Company).values(
        name=name,
        domain=domain,
        ats_type=ats_type,
        ats_identifier=slug,
        country=country,
        priority_score=priority_score,
        scan_frequency_minutes=720,
        next_scan_at=datetime.now(timezone.utc) + timedelta(minutes=10),
        active=True,
    ).on_conflict_do_nothing(index_elements=["name"])
    await db.execute(stmt)


# ── Main discovery ────────────────────────────────────────────────────────────

async def _discover_async(quick: bool = False) -> dict:
    sem   = asyncio.Semaphore(CONCURRENCY)
    found: list[tuple[str, str, str]] = []

    async with httpx.AsyncClient(
        headers={"User-Agent": "JobJarvis/1.0 auto-discovery"},
        follow_redirects=True,
        timeout=10,
    ) as client:

        logger.info("discovery_start", quick=quick)

        # Load CSV companies (built by scripts/build_company_list.py)
        csv_rows    = _load_csv_companies()
        # Build a lookup: name → {domain, priority_score, country}
        csv_meta: dict[str, dict] = {
            row["name"]: row for row in csv_rows
        }
        csv_names = list(csv_meta.keys())

        # Build candidate pool: CSV + YC + SEC EDGAR + hardcoded US companies
        yc_names    = await _fetch_yc_names(client)
        edgar_names = await _fetch_sec_edgar_names(client)
        all_names   = list(dict.fromkeys(
            csv_names + yc_names + edgar_names + _US_COMPANY_NAMES
        ))
        logger.info("discovery_name_pool",
                    csv=len(csv_names), yc=len(yc_names),
                    edgar=len(edgar_names), us=len(_US_COMPANY_NAMES),
                    total=len(all_names))

        # Derive slugs for GH/Lever/Ashby/SR probing
        name_slug_pairs: list[tuple[str, str]] = []
        seen: set[str] = set()
        for name in all_names:
            for slug in _derive_slugs(name)[:2]:
                if slug not in seen:
                    name_slug_pairs.append((name, slug))
                    seen.add(slug)

        # Add known Ashby slugs (exact handles, not derived)
        for slug in _ASHBY_KNOWN_SLUGS:
            if slug not in seen:
                name_slug_pairs.append((slug.replace("-", " ").title(), slug))
                seen.add(slug)

        # Known-slug lists for platform-specific probes
        workable_pairs    = [(s.replace("-", " ").title(), s) for s in _WORKABLE_KNOWN_SLUGS]
        bamboohr_pairs    = [(s.replace("-", " ").title(), s) for s in _BAMBOOHR_KNOWN_SLUGS]
        breezy_pairs      = [(s.replace("-", " ").title(), s) for s in _BREEZY_KNOWN_SLUGS]
        recruitee_pairs   = [(s.replace("-", " ").title(), s) for s in _RECRUITEE_KNOWN_SLUGS]
        workday_pairs     = [(s.replace("-", " ").title(), s) for s in _WORKDAY_KNOWN_SLUGS]
        teamtailor_pairs  = [(s.replace("-", " ").title(), s) for s in _TEAMTAILOR_KNOWN_SLUGS]
        personio_pairs    = [(s.replace("-", " ").title(), s) for s in _PERSONIO_KNOWN_SLUGS]
        icims_pairs       = [(s.replace("-", " ").title(), s) for s in _ICIMS_KNOWN_SLUGS]

        async with AsyncSessionLocal() as db:
            existing = await _get_existing_slugs(db)

        to_test        = [(n, s) for n, s in name_slug_pairs    if s not in existing]
        to_work        = [(n, s) for n, s in workable_pairs     if s not in existing]
        to_bamboo      = [(n, s) for n, s in bamboohr_pairs     if s not in existing]
        to_breezy      = [(n, s) for n, s in breezy_pairs       if s not in existing]
        to_recruitee   = [(n, s) for n, s in recruitee_pairs    if s not in existing]
        to_workday     = [(n, s) for n, s in workday_pairs      if s not in existing]
        to_teamtailor  = [(n, s) for n, s in teamtailor_pairs   if s not in existing]
        to_personio    = [(n, s) for n, s in personio_pairs      if s not in existing]
        to_icims       = [(n, s) for n, s in icims_pairs        if s not in existing]

        if quick:
            to_test       = to_test[:1000]
            to_work       = to_work[:100]
            to_bamboo     = to_bamboo[:100]
            to_breezy     = to_breezy[:100]
            to_recruitee  = to_recruitee[:100]
            to_workday    = to_workday[:50]
            to_teamtailor = to_teamtailor[:100]
            to_personio   = to_personio[:100]
            to_icims      = to_icims[:50]

        logger.info("discovery_candidates",
                    main=len(to_test), workable=len(to_work),
                    bamboohr=len(to_bamboo), breezy=len(to_breezy),
                    recruitee=len(to_recruitee), workday=len(to_workday),
                    teamtailor=len(to_teamtailor), personio=len(to_personio),
                    icims=len(to_icims), existing=len(existing))

        async def probe(name: str, slug: str):
            async with sem:
                if await _check_greenhouse(client, slug):
                    return ("greenhouse", name, slug)
                if await _check_lever(client, slug):
                    return ("lever", name, slug)
                if await _check_ashby(client, slug):
                    return ("ashby", name, slug)
                if await _check_smartrecruiters(client, slug):
                    return ("smartrecruiters", name, slug)
                return None

        async def probe_workable(name: str, slug: str):
            async with sem:
                if await _check_workable(client, slug):
                    return ("workable", name, slug)
                return None

        async def probe_bamboohr(name: str, slug: str):
            async with sem:
                if await _check_bamboohr(client, slug):
                    return ("bamboohr", name, slug)
                return None

        async def probe_breezy(name: str, slug: str):
            async with sem:
                if await _check_breezy(client, slug):
                    return ("breezy", name, slug)
                return None

        async def probe_recruitee(name: str, slug: str):
            async with sem:
                if await _check_recruitee(client, slug):
                    return ("recruitee", name, slug)
                return None

        async def probe_workday(name: str, slug: str):
            async with sem:
                identifier = await _check_workday(client, slug)
                if identifier:
                    return ("workday", name, identifier)
                return None

        async def probe_teamtailor(name: str, slug: str):
            async with sem:
                if await _check_teamtailor(client, slug):
                    return ("teamtailor", name, slug)
                return None

        async def probe_personio(name: str, slug: str):
            async with sem:
                if await _check_personio(client, slug):
                    return ("personio", name, slug)
                return None

        async def probe_icims(name: str, slug: str):
            async with sem:
                if await _check_icims(client, slug):
                    return ("icims", name, slug)
                return None

        results = await asyncio.gather(
            *[probe(n, s)            for n, s in to_test[:BATCH_LIMIT]],
            *[probe_workable(n, s)   for n, s in to_work],
            *[probe_bamboohr(n, s)   for n, s in to_bamboo],
            *[probe_breezy(n, s)     for n, s in to_breezy],
            *[probe_recruitee(n, s)  for n, s in to_recruitee],
            *[probe_workday(n, s)    for n, s in to_workday],
            *[probe_teamtailor(n, s) for n, s in to_teamtailor],
            *[probe_personio(n, s)   for n, s in to_personio],
            *[probe_icims(n, s)      for n, s in to_icims],
        )

        for r in results:
            if r:
                found.append(r)

    # Persist
    inserted = 0
    if found:
        async with AsyncSessionLocal() as db:
            for ats_type, name, slug in found:
                meta = csv_meta.get(name, {})
                await _insert_company(
                    db, name, ats_type, slug,
                    domain=meta.get("domain"),
                    priority_score=meta.get("priority_score", 50),
                    country=meta.get("country", "US"),
                )
                inserted += 1
            try:
                await db.commit()
            except Exception as e:
                logger.error("discovery_commit_error", error=str(e))
                await db.rollback()

    breakdown: dict[str, int] = {}
    for ats, _, _ in found:
        breakdown[ats] = breakdown.get(ats, 0) + 1

    total_tested = (len(to_test) + len(to_work) + len(to_bamboo)
                    + len(to_breezy) + len(to_recruitee)
                    + len(to_workday) + len(to_teamtailor)
                    + len(to_personio) + len(to_icims))
    logger.info("discovery_complete", inserted=inserted,
                breakdown=breakdown, tested=total_tested)
    return {"inserted": inserted, "breakdown": breakdown, "tested": total_tested}
